# Generated by Django 3.0.7 on 2020-07-23 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaccount',
            name='eButton_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 4, 39, 28, 419208, tzinfo=utc)),
        ),
    ]
