# Generated by Django 3.0.6 on 2020-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaccount',
            name='age',
        ),
        migrations.AddField(
            model_name='customaccount',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
