# Generated by Django 3.0.7 on 2020-07-23 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customaccount_ebutton_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='eButton_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 5, 9, 1, 668612, tzinfo=utc)),
        ),
    ]
