# Generated by Django 3.0.7 on 2020-07-23 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200723_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='eButton_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 21, 57, 58, 569963, tzinfo=utc)),
        ),
    ]
