# Generated by Django 3.0.7 on 2020-06-24 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200619_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaccount',
            name='emergency_email',
        ),
    ]
