# Generated by Django 3.0.7 on 2020-07-24 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200724_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='eButton_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 0, 20, 16, 166344, tzinfo=utc)),
        ),
    ]
