language: python

python:
  - "3.7"
  - "3.8"
  - "3.8-dev"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run test suite
script:
  - python manage.py makemigrations
  - python manage.py makemigrations pages
  - python manage.py makemigrations accounts
  - python manage.py migrate
  - python manage.py collectstatic
  - python manage.py test
