# Generated by Django 3.0.7 on 2020-06-29 15:47

import apps.pages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_location', models.CharField(max_length=30)),
                ('trip_name', models.CharField(max_length=30)),
                ('trip_start', models.DateTimeField()),
                ('trip_end', models.DateTimeField()),
                ('trip_status', models.CharField(choices=[(apps.pages.models.TripStatusList_['YTS'], 'Yet to start'), (apps.pages.models.TripStatusList_['IP'], 'In progress'), (apps.pages.models.TripStatusList_['CP'], 'Completed'), (apps.pages.models.TripStatusList_['AR'], 'Awaiting response')], max_length=5)),
                ('trip_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
