# Generated by Django 3.0.7 on 2020-06-19 02:05

import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200611_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(choices=[(apps.pages.models.TripStatusList_['YTS'], 'Yet to start'), (apps.pages.models.TripStatusList_['IP'], 'In progress'), (apps.pages.models.TripStatusList_['CP'], 'Completed'), (apps.pages.models.TripStatusList_['ENS'], 'Emergency notification sent')], default='Yet to start', max_length=5),
            preserve_default=False,
        ),
    ]
