# Generated by Django 3.0.7 on 2020-07-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200629_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='response_sent',
            field=models.BooleanField(default=False),
        ),
    ]
