# Generated by Django 3.0.7 on 2020-07-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_trip_response_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
