# Generated by Django 3.0.7 on 2020-06-24 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_emergencycontact'),
        ('pages', '0003_trip_trip_status'),
    ]

    operations = [
    ]
